mypolls/urls.py
from django.urls import path

from . import views

app_name = 'mypolls'

urlpatterns = [
    # path('', views.index, name='index'),
    # modification to use generic views
    path('', views.IndexView.as_view(), name='index'),
    # ex: /mypolls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # modification to use generic views
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /mypolls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # modification to use generic view
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from mypolls.views import IndexView

urlpatterns = [
    path('mypolls/', include('mypolls.urls')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view())
]

mypolls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mypolls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

'''
# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('mypolls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'mypolls/index.html', context)


# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'mypolls/detail.html', {'question': question})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'mypolls/detail.html', {'question': question})


'''

'''Class based views begin here'''


class IndexView(generic.ListView):
    template_name = 'mypolls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        '''Return the last five published question'''
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'mypolls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'mypolls/results.html'


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'mypolls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print(request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'mypolls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the back button

        return HttpResponseRedirect(reverse('mypolls:results', args=(question.id,)))

mypolls/templates/mypolls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Detail</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'mypolls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>

        {% endfor %}
        <input type="submit" value="Vote" />
    </form>
</body>
</html>

mypolls/templates/mypolls/index.html
{% if latest_question_list %}
     <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'mypolls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
     </ul>

{% else %}
        <p> No polls are available.</p>

{% endif %}

mypolls/templates/mypolls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'mypolls:detail' question.id %}">Vote again?</a>
</body>
</html>